### ISSUE TITLE
Fit and predict ARMA

### ISSUE THREAD

**Issue by luboshanus** [s-broda/ARCHModels.jl#104]
Is there a way how to fit and predict ARMA using this package?

It might useful to Julia users, sice there are not many ways/packages to do it.

Thanks.

**Comment by s-broda** [comment]
Yes:

```julia
julia> fit(ARMA{1, 1}, BG96)

TGARCH{0, 0, 0} model with Gaussian errors, T=1974.

Mean equation parameters:
─────────────────────────────────────────────
      Estimate  Std.Error   z value  Pr(>|z|)
─────────────────────────────────────────────
c   -0.0266446  0.0174716  -1.52502    0.1273
φ₁  -0.621838   0.160738   -3.86864    0.0001
θ₁   0.643588   0.1543      4.17103    <1e-04
─────────────────────────────────────────────

Volatility parameters:
─────────────────────────────────────────
   Estimate  Std.Error  z value  Pr(>|z|)
─────────────────────────────────────────
ω  0.220848  0.0118061  18.7063    <1e-77
─────────────────────────────────────────
```

Automatic lag order selection is also supported:

```julia
julia> selectmodel(ARMA, BG96; minlags=0, maxlags=3)

TGARCH{0, 0, 0} model with Gaussian errors, T=1974.

Mean equation parameters:
────────────────────────────────────────────
     Estimate  Std.Error   z value  Pr(>|z|)
────────────────────────────────────────────
c  -0.0164268  0.0105813  -1.55243    0.1206
────────────────────────────────────────────

Volatility parameters:
─────────────────────────────────────────
   Estimate  Std.Error  z value  Pr(>|z|)
─────────────────────────────────────────
ω  0.221018   0.011801  18.7288    <1e-77
─────────────────────────────────────────
```

**Comment by s-broda** [comment]
Prediction is possible as well:

```
julia> am = fit(ARMA{1, 1}, BG96);
julia> predict(am, :return)
-0.0027370233204087047
```` 
Though I just noticed that predicting more than 1 step ahead appears to be broken.

**Comment by luboshanus** [comment]
Great! Thanks a lot. 

Is there also a way how to change prediction `horizon`? It throws me an error when changing putting something different than `1`.

**Comment by s-broda** [comment]
I've fixed the error, see PR #105. I'll merge it and release Version 2.2.3 as soon as CI is green. Would be great if you could test it more thoroughly once you install the new version, e.g. by comparing the forecasts to some other software like Eviews.

**Comment by shayandavoodii** [comment]
Hi @s-broda,
> Automatic lag order selection is also supported:

After automatically finding lags (let's say the values of $p$ and $q$ in $ARMA(p, q)$), how can I get the value of corresponding coefficients?

**Comment by shayandavoodii** [comment]
Dear @s-broda 
Thank you so much for your response. If you had not told me that, I would have been continuing to build my research on wrong values! I thought the first 6 elements were the coefficients and I was omitting the last element.

> I suppose I could add a convenience method

It would be great! I need the values in my signal processing model, so printing them wouldn't work for me. However, I got the values, such that I mentioned.

> If the distribution has parameters too, those would be returned at the end of the vector.

Which vector? The one that `coef(m)` returns?

**Comment by s-broda** [comment]
>Which vector? The one that `coef(m)` returns?

Yes, though I just noticed that I misremembered: the distribution parameters are returned before the mean parameters. You may find `coefnames` useful:

```julia
julia> m = selectmodel(ARMA, BG96; dist=StdT);
julia> params = (; zip(Symbol.(coefnames(m)), coef(m))...)
(ω = 0.2782287395695833, ν = 2.98700318619116, c = 0.005811678603962783, φ₁ = -0.6307493938587386, θ₁ = 0.6628511611105171)
julia> params.φ₁
-0.6307493938587386
```

**Comment by shayandavoodii** [comment]
> I just noticed that I misremembered: the distribution parameters are returned before the mean parameters.

Thanks for the clarification. I utilized `m.meanspec.coefs` since I did not require distribution parameters. Regardless, I'd like to confirm whether the implementation involves any randomness that might yield varying results each time I fit the model.

**Comment by shayandavoodii** [comment]
> The implementation is deterministic, so the results should always be the same.

It is not. Try the following code:
```julia
tickers = ["AAPL", "MSFT", "AMZN"]
startdt = "2019-01-01"
enddt = "2020-01-01"
data = [get_prices(ticker, startdt=startdt, enddt=enddt)["adjclose"] for ticker in tickers];
prices = stack(data, dims=1)
relprice= prices[:, 2:end]./prices[:, 1:end-1]
p = 3
q = 1
model = fit(ARMA{p, q}, relprice[1, :])
model.meanspec.coefs[2:end]
```
Run it once and save the output. Restart the Julia session, and run the code again. Compare the results to see the difference. In my case, I get these outputs that are not the same:

```
# First run
4-element Vector{Float64}:
 -0.40243685208313973
 -0.11599528938608265
 -0.04534574375574335
  0.361895404259096

# Second run
4-element Vector{Float64}:
 -0.4023807858384195
 -0.11599257495606312
 -0.0453470201698216
  0.36183909740153875
```

Is it possible to fix it? This causes undeterministic results when I employ your package in my projects.
