### ISSUE TITLE
Extension to ARMA-EGARCH?

### ISSUE THREAD

**Issue by alandreed** [s-broda/ARCHModels.jl#29]
Hello Simon.  If a future release were to include integrated fitting of ARMA-EGARCH or ARIMA-EGARCH, it could increase scope/ease of application to some financial data series, hence to usage of the package.

**Comment by s-broda** [comment]
Hi Alan. I've implemented the extension to ARMA-(E)GARCH. Would you mind giving it a spin? I haven't tagged a new release yet, so you'll have to check out the master branch, by doing `add ARCHModels#master` in the Pkg REPL mode (press `]` at the prompt). The documentation is [here](https://s-broda.github.io/ARCHModels.jl/dev/types/#meanspec-1).

Looking forward to any feedback you may have!
Cheers, 
Simon

**Comment by s-broda** [comment]
This should work now.

**Comment by alandreed** [comment]
Hello Simon.  Sorry not to have replied to your 21 Mar post.   I was in a phase of work based on R and Excel.  I’ll come back to trying the analysis in Julia using your new code as soon as I can.  Alan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by s-broda** [comment]
Hi Alan. Would be great if you could kick the tires on this a bit. The code is now in the latest release, so no reason to use the master branch. Just install (or update) the package. 
Cheers
Simon
