### ISSUE TITLE
mention robust vcov

### ISSUE THREAD

**Issue by PaulSoderlind** [s-broda/ARCHModels.jl#58]
Congrats to a nice package.

Two small suggestions wrt. the documention

1. mention somewhere that the vcov is from the robust (sandwich) estimator, not just the inverse of the information matrix.

2. early on, give a simple example like `fit(GARCH{1,1}, data; meanspec=AR{1}, dist=StdNormal)` 

Would you prefer a PR?

**Comment by s-broda** [comment]
Thanks Paul!

Very valid comments, both of them! I'm more than happy to accept a PR if you feel like making one. If you're happy to wait until I get around to changing it myself, that's also OK of course.

Cheers
Simon

**Comment by PaulSoderlind** [comment]
done. see https://github.com/s-broda/ARCHModels.jl/pull/59
